services:
  - type: web
    name: laba10-holidays-api
    env: php
    plan: free
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000"
    envVars:
      - key: PHP_VERSION
        value: "8.0"
